In [2]:
import pandas as pd
#数据读取
df = pd.read_csv("data/sales.csv",usecols=['订单号','产品类别','销售数量','单价'])

#数据处理
df['销售额'] = df['销售数量'] * df['单价']

#数据写入
df.to_csv("data/sales_01.csv",index=False)

In [11]:
#数据查看 --> head , tail ,describe ,info ,shape ,columns
df1 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','销售数量','单价'])
df1.head(10)#显示前十行数据
df1.tail(10)#显示后十行数据
df1.describe()#显示数据统计信息
df1.info()#显示数据信息(列名，非空计数，数据类型)
df1.shape#行和列
df1.columns# 显示列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   销售数量    1000 non-null   int64
 3   单价      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

Index(['订单号', '产品类别', '销售数量', '单价'], dtype='object')

In [23]:
#数据选择
df2 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])

# 1.选择列
# 1.1单列
#df2['订单号']

# 1.2多列
# df2[['产品名称','单价']]
# df2[['产品名称','单价','销售数量']]

# 2.选择行 -- iloc,loc
# 2.1 iloc ----> 基于行号选择行，语法df.iloc[start:stop:step]
# df2.iloc[0:5:1] #不包含结束位置
# df2.iloc[0:5]

# 2.2 loc ----> 基于索引选择行，语法df.loc[start:stop:step]
df2.loc[0::2]

            订单号  产品类别  产品名称  销售数量   单价
0    6805677496  家居用品    枕头    10  199
2    5888085059  电子产品  智能音箱     5  399
4    6801664364    食品    薯片     2   19
6    6857752388    服装    袜子     7  -29
8    5875402232  电子产品   路由器     9  299
..          ...   ...   ...   ...  ...
990  6809488145  电子产品  移动电源     6  149
992  5852186744  电子产品  蓝牙耳机     2  199
994  5860722276    服装    外套     6  599
996  5808511756    食品    坚果     2   79
998  6876456690    食品    果汁     7   39

[500 rows x 5 columns]

In [3]:
df3 = pd.read_csv('data/sales.csv')

# 数据过滤

#1. 获取 销售数量 >= 10的订单数据
# df3[df3['销售数量']>=10]

#2. 获取产品类别 为 食品 或 图书的订单数据
# df3[df3['产品类别'].isin(['食品','图书'])]

#3. 获取单价在 100 - 200之间的订单数据
# df3[df3['单价'].between(100,199,inclusive='left')]  #inclusive 表示是否包含左侧或右侧数据

#4. 获取销售数量 >= 8, 且单价 >= 100的订单数据 ------ 多条件 (并且: & 或者 : |)
# df3[(df3['销售数量']>=8) & (df3['单价']>=100)]

#5. 获取产品类别 为服装/食品，支付方式为支付宝/微信支付 的订单数据
df3[(df3['产品类别'].isin(['服装','食品'])) & (df3['支付方式'].isin(['支付宝','微信支付']))]

            订单号 产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
4    6801664364   食品   薯片     2   19    NaN  微信支付  2025/06/02
10   5808071569   食品  矿泉水     9   29     重庆   支付宝  2025-06-04
16   5812573980   食品   坚果     2   79     南京  微信支付  2025-06-05
23   6867258691   服装   围巾     8  129     青岛  微信支付  2025-06-07
25   6837065480   服装   毛衣     3  399     深圳  微信支付  2025-06-07
..          ...  ...  ...   ...  ...    ...   ...         ...
993  6870828210   服装   内衣     8   89     广州  微信支付  2026-03-20
994  5860722276   服装   外套     6  599     广州  微信支付  2026-03-20
996  5808511756   食品   坚果     2   79     成都   支付宝  2026-03-20
997  5811169466   服装   围巾     4  129     南京   支付宝  2026-03-20
998  6876456690   食品   果汁     7   39     广州   支付宝  2026-03-20

[297 rows x 8 columns]